version: "3"
services:

  typo3:
    image: crinis/typo3:6.2-php5.6-apache
    volumes:
      - typo3:/var/www/html/
    ports:
      - 80:80
    networks:
      - db

  mysql:
    image: mysql:5.6
    volumes:
     - mysql:/var/lib/mysql/
    networks:
      - db
    environment:
      MYSQL_DATABASE: 'typo3'
      MYSQL_USER: 'typo3'
      MYSQL_PASSWORD: 'ShouldBeAStrongPassword'
      MYSQL_ROOT_PASSWORD: 'ShouldBeAStrongPassword'
    command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'

networks:
  db:

volumes:
  typo3:
  mysql:
